/**
 * @File Name          : StripePaymentRequest.cls
 * @Description        : 
 * @Author             : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Group              : 
 * @Last Modified By   : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Last Modified On   : 4/17/2020, 2:45:07 PM
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    4/17/2020   ChangeMeIn@UserSettingsUnder.SFDoc     Initial Version
**/
public with sharing class StripePaymentRequest {
    public StripePaymentRequest() {

    }   
}
